plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'net.nex.discordlink'
version = '1.0.4'

repositories {
    mavenCentral()
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.17.1'
    compileOnly 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'com.warrenstrange:googleauth:1.5.0'
    implementation 'com.google.zxing:core:3.5.1'
    implementation 'com.google.zxing:javase:3.5.1'
    implementation('net.dv8tion:JDA:5.0.0-beta.18') {
        exclude module: 'opus-java'
    }
    implementation 'com.zaxxer:HikariCP:5.0.1'
    implementation 'org.xerial:sqlite-jdbc:3.53.2.1'
    implementation 'com.mysql:mysql-connector-j:9.4.0'
    implementation 'org.bstats:bstats-bukkit:3.0.2'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testImplementation 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release = targetJavaVersion
    }
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}

shadowJar {
    mergeServiceFiles()
    relocate 'net.dv8tion.jda', 'net.nex.discordlink.libs.jda'
    relocate 'org.bstats', 'net.nex.discordlink.libs.bstats'
    relocate 'com.zaxxer.hikari', 'net.nex.discordlink.libs.hikari'
    relocate 'org.slf4j', 'net.nex.discordlink.libs.slf4j'
    relocate 'com.google.zxing', 'net.nex.discordlink.libs.zxing'
    relocate 'com.warrenstrange', 'net.nex.discordlink.libs.googleauth'
    archiveClassifier.set('')
}

jar {
    archiveClassifier.set('original')
}

tasks.build.dependsOn tasks.shadowJar
